SELECT
    I.SEQPRODUTO,
    I.DESCRICAOPRODXML AS DESCRICAO_PRODUTO, 
    SUM(I.QUANTIDADE) AS QUANTIDADE,
    'R$ ' || TO_CHAR(MAX(C.PRECOVALIDNORMAL), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') AS PRECO_ATUAL
FROM 
    MLF_NFITEM I
    INNER JOIN MRL_PRODEMPSEG C 
        ON I.SEQPRODUTO = C.SEQPRODUTO
        AND I.NROEMPRESA = C.NROEMPRESA
        AND C.STATUSVENDA = 'A'
WHERE 
    I.SEQPESSOA = :NR2
    AND I.DTAMOVTOITEM BETWEEN :DT1 AND :DT2 
    AND I.NROEMPRESA = :NR1
GROUP BY 
    I.SEQPRODUTO, I.DESCRICAOPRODXML;