SELECT 
    CASE 
        WHEN t.NROEMPRESA = 1 THEN '1- Matriz' 
        WHEN t.NROEMPRESA = 2 THEN '2- Cruzeiro' 
        WHEN t.NROEMPRESA = 3 THEN '3- Tianguá' 
        ELSE 'Outro' 
    END AS LOJA, 
    t.SEQPESSOA AS PESSOA, 
    p.NOMERAZAO AS FORNECEDOR, 
    t.CODESPECIE AS ESPECIE, 
    t.NROTITULO AS NRO_TITULO, 
    t.NROPARCELA AS PARCELA, 
    t.QTDPARCELA AS QTD_PARCELAS, 
    'R$ '||TO_CHAR(ROUND(t.VLRNOMINAL, 2), 'FM999G999G999D90', 'nls_numeric_characters='',.''')AS VALOR,
    TO_CHAR(t.DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO, 
    TO_CHAR(t.DTAMOVIMENTO, 'DD/MM/YYYY') AS DATA_ENTRADA, 
    UPPER(t.USUALTERACAO) AS USUARIO, 
    TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DATA_IMPRESSAO
    FROM FI_TITULO t 
        JOIN ge_pessoa p ON p.SEQPESSOA = t.SEQPESSOA 
    WHERE t.NROEMPRESA = :LT2 
        AND t.USUALTERACAO = UPPER(:LT1) 
        AND t.DTAMOVIMENTO BETWEEN :DT1 AND :DT2 
        AND  t.VLRNOMINAL != 0;